### ISSUE TITLE
Installation section

### ISSUE THREAD

**Issue by lfarah** [SwiftStudies/Duration#2]
Hey @SwiftStudies, your library is really interesting.

The only problem I found was the `README.md`, which is a little bit confusing.
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to organize the lib.

What are your thoughts?

**Comment by SwiftStudies** [comment]
Again, happy to consider a pull request!  Propose away 🙂

**Comment by SwiftStudies** [comment]
Closing, will become a pull
